# Site settings
title: GeoBlacklight
email: geoblacklight-working-group@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  An easier way to find geospatial data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geoblacklight.org" # the base hostname & protocol for your site
twitter_username: geoblacklight
github_username:  geoblacklight
collections:
  projects:
    output: true
# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - bourbon
  - neat
  - bitters
assets:
  sources:
    - _assets/fonts