site_name: GeoBlacklight
site_url: https://geoblacklight.org
theme:
  name: material
  custom_dir: overrides
  logo: images/geoblacklight-logo.png
  favicon: images/favicon.png
  palette:
    primary: white
        
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - tags: {}
      index_page: tags.md
          
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-cards.css
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - neoteroi.cards
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
 
plugins:
  - search
  - tags: 
      tags_file: tags.md

#   - blogging:
#       theme:
#         name: card
#       dirs: # The directories to be included
#         - blog
#       template: overrides/custom-blog.html
#       features:
#             tags:
#                   index_page: tags.md
#                   insert: top
#       categories:
#         - name: '2023'
#           dirs:
#             - blog/2023
#         - name: '2022'
#           dirs:
#              - blog/2022

nav:
- Home: 'index.md'
- About: 'about.md'
- Showcase: 
      - showcase/index.md
- Connect: 'connect.md'
- Blog:
      - blog/index.md
- Documentation: 'https://geoblacklight.org/docs'



