site_name: GeoBlacklight
site_url: https://geoblacklight.org
copyright: GeoBlacklight Community &copy; 2015 - 2024
theme:
  name: material
  logo: images/gbl-favicon.png
  favicon: images/gbl-favicon.png
  
        
  palette:
    primary: white
    
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - tags: {}
      index_page: tags.md


extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
plugins:
  - search
  - table-reader
  - blog:
      blog_dir: blog
#       blog_toc: true
#       categories_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM
      post_excerpt: optional
      authors: true
      authors_file: blog/.authors.yml
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  
extra:
      social:
          - icon: fontawesome/brands/github 
            link: https://github.com/GeoBlacklight
          - icon: fontawesome/brands/slack
            link: https://geoblacklight.slack.com
          - icon: fontawesome/solid/paper-plane
            link: https://groups.google.com/g/geoblacklight-working-group

nav:
- Home: 'index.md'
- About: 'about.md'
- Community: 'community.md'
- Showcase: 
      - showcase/index.md
- Blog:
      - blog/index.md
      
- Documentation:
      - Install:
            - 'Quick Start': 'documentation/geoblacklight_quick_start.md'
            - 'Getting Started - Developers Guide': 'documentation/getting_started_developers.md'
            - 'Tutorials': 'documentation/tutorials.md'
      
      - Upgrade:
            - 'Upgrade to Version 4.0': 'documentation/upgrade_version_4_0.md'
            - 'Upgrade to Version 2.0': 'documentation/upgrade_version_2_0.md'
      
      - Customization:
            - 'Configure the Settings': 'documentation/settings.md'
            - 'Update the Catalog Controller': 'documentation/catalog_controller.md'  
            - 'Customize Leaflet': 'documentation/leaflet.md'
            - 'Add Mirador IIIF Viewer': 'documentation/adding_mirador_viewer.md'
            - 'Add Thumbnail Images': 'documentation/item_images.md'
            - 'Add SVG Icons': 'documentation/adding_svg_icons.md'
            - 'Add Data Relations Widget': 'documentation/data_relations_widget.md'
            - 'Render HTML in Metadata Fields': 'documentation/rendering_html_from_description.md'
            
      - Running in Production:
            - 'Hardware Recommendations': 'documentation/hardware_recommendations.md'
            - 'Implementation Recommendations': 'documentation/implementation_recommendations.md'
            - 'Periodic Maintenance': 'documentation/periodic_maintenance.md'
      - Reference:
            - 'Glossary': 'documentation/glossary.md'
            - 'Settings.yml fields': 'documentation/settings-yml.md'
            - 'Metadata Fields': 'documentation/metadata.md'
            - 'Software Releases': 'documentation/releases.md'    
            - 'Index Maps': 'documentation/index_maps.md'
            - 'GeoPackages': 'documentation/geopackages.md'
            - 'JSONs and GeoJSONs': 'documentation/json-geojson.md'

     



