INHERIT: mkdocs-base.yml

docs_dir: docs

plugins:
  - search
  - git-revision-date-localized
  - blog:
      blog_dir: blog
      #       blog_toc: true
      #       categories_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM
      post_excerpt: optional
      authors: true
      authors_file: blog/.authors.yml
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeoBlacklight
    - icon: fontawesome/brands/slack
      link: https://geo4lib.slack.com
    - icon: fontawesome/solid/paper-plane
      link: https://groups.google.com/g/geo4lib-community

nav:
  - Home: "index.md"
  - About: "about.md"
  - Community: "community.md"
  - Showcase:
      - showcase/index.md
  - Blog:
      - blog/index.md
  - Release Calendar: "releases.md"
