[project]
name = "geoblacklight.github.io"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "mike>=2.2.0",
    "mkdocs>=1.6.1",
    "mkdocs-git-revision-date-localized-plugin>=1.5.1",
    "mkdocs-material>=9.7.6",
    "mkdocs-material-extensions>=1.3.1",
    "mkdocs-table-reader-plugin>=3.1.0",
    "pymdown-extensions>=10.21.2",
]

[tool.setuptools]
packages = []
py-modules = []

[tool.uv]
package = false
