name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for correct revision dates in commits
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - run: pip install -r requirements.txt
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: mike deploy --push 5.x
